### PR TITLE
Updates for 0.3.4

### PR DESCRIPTION
**Pull request by tmarble**
* Updated test rubrics: test/data/main.{htn,tpn}.{json,edn}
* Import fixes to utils/ read-json-str and write-json-str include
  - proper keywordization (including preserving namespaces),
  - handling merged maps and not escaping slash.
* Significant improvements to testing macro match-eval-out-err
  - Support Java pattern matching options (e.g. :case-insensitive)
  - Add invert matching option (returns opposite of match result)
  - Prints first form to EVAL on stdout (to better track down
    which part of the test passes or fails)
* Extended coercion by adding delay-activity-slots-optional
* Default logging messages now sent to STDERR (instead of STDOUT)

Signed-off-by: Tom Marble <tmarble@info9.net>

### CODE REVIEW

**Review by dcerys — COMMENTED** [review]
In /src/plan_schema/cli.clj
The if/then blocks beginning at line 166 are identical, except for the `catch`.  
Would it be clearer to define a local function, and then call that from both sides of the `if`?

**Comment by pmdoll** [comment]
In src/plan_schema/utils.clj, 
```
(plan-schema.utils/read-json-str (slurp "test/data/main.tpn.json"))
=>
{:da-196 {:tpn-type "delay-activity",
          :uid "da-196",
          :constraints ["tc-195"],
          :end-node "node-214",
          :label "TEMP-delay",
...
Seems to be working fine. So where is the need to escape strings? Where is the data coming from that requires the implemented fixes?

On a side note,
error? fn in utils.clj, seems to be taking a string and parsing it using `read-json-string` and reading :errors from clojure data structure. But in the preceding `action` function we must have the same data as clj data structure so it seems that converting clj to string and back to clj could be avoided. 
```

**Comment by tmarble** [comment]
@dcerys I have addressed your concern in  a3ef448

@pmdoll I don't really understand this (escape strings) question, 
but I'm guessing you're wondering why strings need to be escaped in
`test/testing/plan_schema/cli.clj`. The tesing macro
`match-eval-out-err` will execute a form (in this case a command line
invocation) and check that the exit code, STDOUT and/or STDERR conform
to expectations. The streams are typically either the contents of an
EDN file or JSON file returned as a string. If special characters such
as quote `"` occur in the stream must be matched then they must be escaped.

In this way `match-eval-out-err` provides a much stronger
test that simply verifying the return code: it also checks
that outputs are at least "sane" and, for example, STDERR does not
contain any "ERROR" messages.

_Where is the data coming from that requires the implemented fixes?_

I don't know which fixes you are referring to, but I'm guessing
you mean the changes to coerce.clj and utils.clj.
- In coerce.clj `delay-activity-slots-optional` now allows
  the slots **:label** and **:display-name** to be optional
  (previously caused a warning).
- As we agreed we want to test merged maps here in plan-schema
  (to avoid discovering merge problems when actually used with planviz).
  The form of a merged file is a vector of two maps (one for the HTN
  and the other for the TPN). Previously read-json-str was hardcoded
  to only expect a map.
- Passing the :key-fn to json/read-str avoids our need to
  keywordize the map. The arity 1 version of read-json-string
  (in the case of a merged map) takes a string which is converted
  to JSON, which is then an array of two maps passed again to
  the arity 1 version, then each map is passed to the artity 3
  version (using reduce-kv). In this way we ensure conversion
  is consistent.
- write-json-str had to change for two reasons. First without
  the specialized :key-fn namespaced keys lost their namespace
  (causing the EDN->JSON->EDN round trip tests to fail).
  Second (in support of the above) the default behavior to escape
  slashes needed to be turned off.

Regarding your side note.. That would be the case if we *always* got EDN returned from all
of the actions. However one of the options is the :file-format
which could be JSON. So what we need to determine is if we have
a map (in either EDN or JSON) that has an :error (or "error") key
with an error message value. This is how we can determine
of one of the plan-schema library functions failed with an
error such that a non-zero exit code can be returned.

**Comment by pmdoll** [comment]
*Regarding your side note.. That would be the case if we always got EDN returned from all
of the actions. However one of the options is the :file-format
which could be JSON. So what we need to determine is if we have
a map (in either EDN or JSON) that has an :error (or "error") key
with an error message value. This is how we can determine
of one of the plan-schema library functions failed with an
error such that a non-zero exit code can be returned.*

So each and every *action* function is responsible for converting to appropriate format. But if we change the responsibility of *action* functions to give only edn,  perform *error?* checks on edn and then delegate writing to  appropriate function, then we could avoid edn-json-edn conversion.

**Comment by tmarble** [comment]
@pmdoll if that's what you want you can change it. Basically what that would mean is the :file-format option is ignored by all the plan-schema library functions and the *caller* will be responsible for transforming the EDN to JSON if required. Please let me know if the library and the consumers (pamela and plan-schema) should adopt this behavior.

**Comment by tmarble** [comment]
Obsoleted by PR #35 and PR #36

**Pull request closed without merging**
